// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Install(arg1) {
  return window['go']['gui']['App']['Install'](arg1);
}

export function SystemInfo() {
  return window['go']['gui']['App']['SystemInfo']();
}
