// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {installer} from '../models';

export function Install(arg1:string):Promise<installer.Result>;

export function SystemInfo():Promise<{[key: string]: string}>;
